# Bug 7: bad infinite loop management

default: infinite

targets:

  infinite:
    steps:
    - call: infinite-1
    - call: infinite-2
    - call: infinite-3
    - call: infinite-4

  infinite-1:
    steps:
    - try:
      - neon: 'infinite-1.tst'
      catch:
      - throw: 'Test infinite 1 failed'

  infinite-2:
    steps:
    - 'fail = false'
    - try:
      - neon: 'infinite-2.tst'
      - 'fail = true'
      catch:
      - if: >
          _error != "running build 'infinite-2.tst': running target 'test1': in step 2: running target 'test2': in step 2: running target 'test1': infinite loop: test1 -> test2 -> test1"
        then:
        - throw: "Bad error message: ={_error}"
    - if: fail
      then:
      - throw: 'Test infinite 2 failed'

  infinite-3:
    steps:
    - try:
      - neon: 'infinite-3.tst'
      catch:
      - throw: 'Test infinite 3 failed with error: ={_error}'

  infinite-4:
    steps:
    - try:
      - neon: 'infinite-4.tst'
      catch:
      - throw: 'Test infinite 4 failed with error: ={_error}'
